raid:
  environment: dev
  isni-client:
    url-format: http://localhost:1080/sru/?query=pica.isn+%3D+%22__ISNI__%22&operation=searchRetrieve&recordSchema=isni-b
  orcid-client:
    base-url: http://localhost:1080/v3.0/
    access-token: 32cacfb3-6dab-4554-ae51-22efd37a2463
  ror-client:
    client-id: 08VB3D1YYHC63CQ8QHP0TBD0I6RULCHQ
    base-url: http://localhost:1080/v2/
  db:
    user: postgres
    password: supersecret
    host: localhost
    port: 7432
    name: raido
    encryption-key: pB7MB3iuYmmjWMTOCK6HS0JetzWhCtBtKoNl39pBr3Q=
  iam:
    realm-uri: http://localhost:8001/realms/raid
  raid-permissions:
    client-id: raid-permissions-admin
    client-secret: 07ATOSG9hYs8oATcz5wcQAdRuoEsLzEY
  contributor-validation:
    orcid:
      url-prefix: https://sandbox.orcid.org/
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-secret: Nr0HycAztrRSNehq9EZR2wKvqmpC3JfS
datacite:
  endpoint: http://localhost:1080/dois