[versions]
keycloak-server-spi = "24.0.1"
keycloak-server-spi-private = "24.0.1"
keycloak-core = "24.0.1"
keycloak-services = "24.0.1"
lombok = "1.18.30"
jakarta-jakartaee-web-api = "9.1.0"
slf4j-simple = "2.0.6"
junit-jupiter = "5.9.1"
mockito-core = "5.11.0"
hamcrest = "2.2"
commons-math3 = "3.6.1"
guava = "31.1-jre"
jackson-databind = "2.13.4.2"
jakarta-validation-api = "3.0.2"
annotations = "13.0"
flyway-core = "9.22.3"
geonames-ws-client = "1.1.17"
jackson-datatype-jsr310 = "2.20.0"
jackson-annotations = "2.15.2"
jakarta-json-api = "2.1.3"
jakarta-json = "1.1.5"
jakarta-xml-bind-api = "4.0.4"
jaxb-runtime = "4.0.6"
mockito-inline = "4.11.0"
spring-security-test = "6.2.2"
jaxb-xjc = "3.0.2"
jakarta-annotation-api = "2.1.1"
jena-arq = "4.7.0"
postgresql = "42.5.4"
commons-compress = "1.26.2"

[libraries]
keycloak-server-spi = { group = "org.keycloak", name = "keycloak-server-spi", version.ref = "keycloak-server-spi" }
keycloak-server-spi-private = { group = "org.keycloak", name = "keycloak-server-spi-private", version.ref = "keycloak-server-spi-private" }
keycloak-core = { group = "org.keycloak", name = "keycloak-core", version.ref = "keycloak-core" }
keycloak-services = { group = "org.keycloak", name = "keycloak-services", version.ref = "keycloak-services" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
jakarta-jakartaee-web-api = { group = "jakarta.platform", name = "jakarta.jakartaee-web-api", version.ref = "jakarta-jakartaee-web-api" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j-simple" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito-core" }
hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }
commons-math3 = { group = "org.apache.commons", name = "commons-math3", version.ref = "commons-math3" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson-databind" }
jakarta-validation-api = { group = "jakarta.validation", name = "jakarta.validation-api", version.ref = "jakarta-validation-api" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
flyway-core = { group = "org.flywaydb", name = "flyway-core", version.ref = "flyway-core" }
geonames-ws-client = { group = "org.geonames", name = "geonames-ws-client", version.ref = "geonames-ws-client" }
jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jackson-datatype-jsr310" }
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson-annotations" }
jakarta-json-api = { group = "jakarta.json", name = "jakarta.json-api", version.ref = "jakarta-json-api" }
jakarta-json = { group = "org.eclipse.parsson", name = "jakarta.json", version.ref = "jakarta-json" }
jakarta-xml-bind-api = { group = "jakarta.xml.bind", name = "jakarta.xml.bind-api", version.ref = "jakarta-xml-bind-api" }
jaxb-runtime = { group = "org.glassfish.jaxb", name = "jaxb-runtime", version.ref = "jaxb-runtime" }
mockito-inline = { group = "org.mockito", name = "mockito-inline", version.ref = "mockito-inline" }
spring-security-test = { group = "org.springframework.security", name = "spring-security-test", version.ref = "spring-security-test" }
jaxb-xjc = { group = "org.glassfish.jaxb", name = "jaxb-xjc", version.ref = "jaxb-xjc" }
jakarta-annotation-api = { group = "jakarta.annotation", name = "jakarta.annotation-api", version.ref = "jakarta-annotation-api" }
jena-arq = { group = "org.apache.jena", name = "jena-arq", version.ref = "jena-arq" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
commons-compress = { group = "org.apache.commons", name = "commons-compress", version.ref = "commons-compress" }
